import React, { createContext, useContext, useState } from "react";

export const translations = {
  id: {
    // Navigation / Sidebar
    dashboard: "Dasbor",
    accounts: "Rekening",
    transactions: "Transaksi",
    income: "Pemasukan",
    expenses: "Pengeluaran",
    budget: "Anggaran",
    settings: "Pengaturan",
    profile: "Profil",
    logout: "Keluar",

    // Auth
    loginTitle: "Masuk ke Akun",
    loginSubtitle: "Gunakan email dan kata sandi Anda",
    emailLabel: "Alamat Email",
    passwordLabel: "Kata Sandi",
    forgotPassword: "Lupa kata sandi?",
    loginButton: "Masuk ke Akun",
    noAccount: "Belum punya akun?",
    registerFree: "Daftar gratis",
    registerTitle: "Buat Akun Baru",
    registerSubtitle: "Mulai perjalanan finansial Anda hari ini",
    fullNameLabel: "Nama Lengkap",
    fullNamePlaceholder: "Mis. Caesa Putra",
    registerButton: "Buat Akun Saya",
    alreadyHaveAccount: "Sudah punya akun?",
    loginHere: "Masuk",

    // Transactions Client
    transactionsTitle: "Transaksi",
    transactionsSubtitle: "Kelola dan telusuri pemasukan, pengeluaran, dan transfer.",
    export: "Ekspor",
    addTransaction: "Tambah Transaksi",
    totalTransactions: "Total Transaksi",
    incomeLabel: "Pemasukan",
    expenseLabel: "Pengeluaran",
    detailsHeader: "Rincian Transaksi",
    categoryHeader: "Kategori",
    amountHeader: "Jumlah",
    dateRangeLabel: "Rentang Tanggal",
    startDateLabel: "Tanggal mulai",
    endDateLabel: "Tanggal akhir",
    applyFilter: "Terapkan Filter",
    resetFilter: "Reset",
    searchPlaceholder: "Cari deskripsi atau catatan...",
    allTypes: "Semua tipe",
    allAccounts: "Semua akun",
    allCategories: "Semua kategori",
    noCategory: "Tanpa kategori",
    editOption: "Ubah",
    duplicateOption: "Duplikasi",
    deleteOption: "Hapus",
    cancelButton: "Batal",
    deleteSelected: "Hapus Terpilih",
    selectedCount: "transaksi terpilih",
    confirmBulkTitle: "Hapus Transaksi Terpilih",
    confirmBulkDesc: "Apakah Anda yakin ingin menghapus {count} transaksi terpilih? Tindakan ini tidak dapat dibatalkan dan saldo akun terkait akan disesuaikan kembali secara otomatis.",
    transactionCount: "transaksi",
    transferLabel: "Transfer",
    transferFund: "Transfer Dana",
    noDescription: "Tanpa Deskripsi",
    receiptLabel: "Struk",
    viewReceipt: "Lihat Struk",
    activeFilter: "Filter Aktif",
    deleteTransaction: "Hapus transaksi",
    deleteTransactionDesc: "Saldo akun akan disesuaikan otomatis.",
    deleteTransferDesc: "Saldo akun sumber dan akun tujuan akan dikoreksi otomatis.",
    deletingLabel: "Menghapus...",
    exportImport: "Ekspor / Impor",
    noMatchingTransactions: "Tidak ada transaksi cocok",
    noMatchingDesc: "Coba ubah kata kunci atau reset filter.",
    noTransactions: "Belum ada transaksi",
    noTransactionsDesc: "Catat transaksi pertama Anda untuk mulai melacak arus kas.",
    addAccountFirst: "Tambahkan akun terlebih dahulu untuk mencatat transaksi.",

    // App Layout
    connectingToApp: "Menghubungkan ke Maybe Finance...",

    // Transactions (extra)
    tableView: "Tabel",
    calendarView: "Kalender",
    cashFlowCalendar: "Kalender Arus Kas",
    transactionsOn: "Transaksi Pada",
    noTransactionsOnDay: "Tidak ada transaksi tercatat pada tanggal ini.",
    ofTotal: "dari total",
    selectAllOnPage: "Pilih semua di halaman ini",
    transactionOptions: "Opsi transaksi",
    showing: "Menampilkan",
    from: "dari",
    perPage: "Per halaman",
    filtered: "Terkirim",
    incomeShort: "Masuk",
    expenseShort: "Keluar",
    addAccountFirstTitle: "Tambahkan akun terlebih dahulu",
    exportSuccessJson: "Berhasil mengekspor JSON",
    exportFailed: "Gagal mengekspor data",
    deleteSuccess: "Transaksi berhasil dihapus",
    deleteFailed: "Gagal menghapus transaksi",
    deleteBulkFailed: "Gagal menghapus transaksi terpilih",

    // Budget
    budgetTitle: "Anggaran Bulanan",
    totalBudget: "Total Anggaran",
    totalSpent: "Total Pengeluaran",
    remaining: "Sisa",
    noBudgetSet: "Belum ada anggaran",
    setBudget: "Atur Anggaran",
    editBudget: "Ubah Anggaran",
    deleteBudget: "Hapus Anggaran",
    spent: "Terpakai",
    overBudget: "Melebihi anggaran",
    underBudget: "Dalam anggaran",

    // Settings
    settingsTitle: "Pengaturan",
    categoriesTab: "Kategori",
    apiKeysTab: "API Keys",
    themeTab: "Tema",
    addCategory: "Tambah Kategori",
    deleteCategory: "Hapus kategori",
    categoryDeleted: "Kategori berhasil dihapus",
    categoryDeleteFailed: "Gagal menghapus kategori",
    categoryCreated: "Kategori berhasil ditambahkan",
    categoryCreateFailed: "Gagal menambahkan kategori",
    confirmDeleteCategory: "Apakah Anda yakin ingin menghapus",
    categoryDeleteWarning: "Transaksi yang menggunakan kategori ini akan dikosongkan kategorinya (data transaksi tetap aman).",

    // Investments
    investments: "Investasi",
    portfolio: "Portofolio",
    totalValue: "Total Nilai",
    totalCost: "Total Modal",
    totalPnl: "Total Laba/Rugi",
    buyAsset: "Beli Aset",
    sellAsset: "Jual Aset",
    updatePrice: "Update Harga",
    noInvestments: "Belum ada aset investasi",
    quantity: "Jumlah",
    buyPrice: "Harga Beli",
    currentPrice: "Harga Saat Ini",
    marketValue: "Nilai Pasar",
    pnl: "Laba/Rugi",

    // Goals
    goals: "Target Tabungan",
    addGoal: "Tambah Target",
    goalsPageSubtitle: "Kelola rencana dan target finansial masa depan Anda.",
    targetAmount: "Jumlah Target",
    currentAmount: "Terkumpul",
    targetDate: "Target Tanggal",
    totalTargetAmount: "TOTAL TARGET AKUMULATIF",
    totalSaved: "TOTAL TERKUMPUL",
    averageProgress: "RATA-RATA PROGRES",
    noGoalsSet: "Belum ada target tabungan",
    noGoalsDesc: "Tentukan rencana finansial Anda hari ini seperti liburan, dana darurat, atau beli rumah!",
    createFirstGoal: "Buat Target Pertama",
    dueLabel: "Target:",
    deleteGoalTitle: "Hapus Target Tabungan?",
    deletePermanentDesc: "Tindakan ini permanen dan tidak dapat dibatalkan.",
    goalUpdateSuccess: "Target tabungan berhasil diperbarui",
    goalAddSuccess: "Target tabungan berhasil ditambahkan",
    goalDeleteSuccess: "Target tabungan berhasil dihapus",
    goalDeleteFailed: "Gagal menghapus target",
    pctNiceStart: "Awal Bagus",
    pctHalfway: "Setengah Jalan",
    pctAlmostDone: "Hampir Tercapai",
    pctCompleted: "Tercapai!",
    projectionDueNow: "Butuh segera!",
    projectionAchieved: "Tercapai! 🎉",
    projectionLeft: "lagi",
    projectionMonth: "/ bln",
    valGoalNameRequired: "Nama target harus diisi",
    valGoalTargetAmount: "Target nominal harus lebih besar dari 0",
    valGoalCurrentAmount: "Nominal terkumpul tidak valid",
    valGoalDateRequired: "Tanggal target harus diisi",
    valGoalSaveFailed: "Gagal menyimpan",
    editGoalTitle: "Ubah Target Tabungan",
    newGoalTitle: "Target Tabungan Baru",
    goalSubtitle: "Ukur dan lacak tujuan finansialmu.",
    goalNameLabel: "Nama Target",
    goalNamePlaceholder: "Mis. Beli Laptop Baru",
    linkedAccountLabel: "Hubungkan ke Akun (Opsional)",
    noAccountLinked: "Tanpa rekening",
    selectAccountPlaceholder: "Pilih rekening",
    noteOptionalLabel: "Catatan (opsional)",
    noteOptionalPlaceholder: "Mis. Sisihkan dari bonus tahunan",
    savingLabel: "Menyimpan...",
    saveChanges: "Simpan Perubahan",
    selectDatePlaceholder: "Pilih Tanggal",

    // Recurring
    recurring: "Tagihan Rutin",
    addRecurring: "Tambah Tagihan",
    frequency: "Frekuensi",
    autoPay: "Bayar Otomatis",
    nextPayment: "Pembayaran Berikutnya",
    billSchedule: "Jadwal Tagihan & Langganan",
    totalMonthlyCommitment: "TOTAL BULANAN",
    activeSubscriptions: "LAYANAN AKTIF",
    setupBill: "Pasang Tagihan",
    payNow: "Bayar Sekarang",
    deleteRecurringTitle: "Hapus Tagihan Berulang?",
    deleteRecurringDesc: "Apakah Anda yakin ingin menghapus tagihan berulang ini?",

    // Theme Settings
    themeCustomizer: "Kustomisasi Tema",
    customThemeLabel: "Warna Tema Kustom",
    accentColor: "Warna Aksen",
    canvasColor: "Warna Canvas",
    surfaceColor: "Warna Kartu/Panel",
    borderColor: "Warna Border",
    successColor: "Warna Pemasukan",
    dangerColor: "Warna Pengeluaran",
    saveTheme: "Simpan Desain Tema",
    resetTheme: "Kembalikan Tema Default",

    // Common
    save: "Simpan",
    cancel: "Batal",
    delete: "Hapus",
    edit: "Ubah",
    create: "Buat",
    loading: "Memuat...",
    error: "Terjadi kesalahan",
    success: "Berhasil",
    confirm: "Konfirmasi",
  },
  en: {
    // Navigation / Sidebar
    dashboard: "Dashboard",
    accounts: "Accounts",
    transactions: "Transactions",
    income: "Income",
    expenses: "Expenses",
    budget: "Budget",
    settings: "Settings",
    profile: "Profile",
    logout: "Logout",

    // Auth
    loginTitle: "Log in to Account",
    loginSubtitle: "Use your email and password",
    emailLabel: "Email Address",
    passwordLabel: "Password",
    forgotPassword: "Forgot password?",
    loginButton: "Log In",
    noAccount: "Don't have an account?",
    registerFree: "Sign up for free",
    registerTitle: "Create New Account",
    registerSubtitle: "Start your financial journey today",
    fullNameLabel: "Full Name",
    fullNamePlaceholder: "e.g., Caesa Putra",
    registerButton: "Create My Account",
    alreadyHaveAccount: "Already have an account?",
    loginHere: "Log In",

    // Transactions Client
    transactionsTitle: "Transactions",
    transactionsSubtitle: "Manage and track income, expenses, and transfers.",
    export: "Export",
    addTransaction: "Add Transaction",
    totalTransactions: "Total Transactions",
    incomeLabel: "Income",
    expenseLabel: "Expenses",
    detailsHeader: "Transaction Details",
    categoryHeader: "Category",
    amountHeader: "Amount",
    dateRangeLabel: "Date Range",
    startDateLabel: "Start date",
    endDateLabel: "End date",
    applyFilter: "Apply Filters",
    resetFilter: "Reset",
    searchPlaceholder: "Search description or note...",
    allTypes: "All types",
    allAccounts: "All accounts",
    allCategories: "All categories",
    noCategory: "Uncategorized",
    editOption: "Edit",
    duplicateOption: "Duplicate",
    deleteOption: "Delete",
    cancelButton: "Cancel",
    deleteSelected: "Delete Selected",
    selectedCount: "transactions selected",
    confirmBulkTitle: "Delete Selected Transactions",
    confirmBulkDesc: "Are you sure you want to delete {count} selected transactions? This action cannot be undone and corresponding account balances will be adjusted automatically.",
    transactionCount: "transactions",
    transferLabel: "Transfer",
    transferFund: "Fund Transfer",
    noDescription: "No Description",
    receiptLabel: "Receipt",
    viewReceipt: "View Receipt",
    activeFilter: "Active Filter",
    deleteTransaction: "Delete transaction",
    deleteTransactionDesc: "Account balance will be adjusted automatically.",
    deleteTransferDesc: "Source and target account balances will be corrected automatically.",
    deletingLabel: "Deleting...",
    exportImport: "Export / Import",
    noMatchingTransactions: "No matching transactions",
    noMatchingDesc: "Try changing keyword or resetting filters.",
    noTransactions: "No transactions yet",
    noTransactionsDesc: "Record your first transaction to start tracking cash flow.",
    addAccountFirst: "Add an account first to record transactions.",

    // App Layout
    connectingToApp: "Connecting to Maybe Finance...",

    // Transactions (extra)
    tableView: "Table",
    calendarView: "Calendar",
    cashFlowCalendar: "Cash Flow Calendar",
    transactionsOn: "Transactions on",
    noTransactionsOnDay: "No transactions recorded on this day.",
    ofTotal: "of total",
    selectAllOnPage: "Select all on this page",
    transactionOptions: "Transaction options",
    showing: "Showing",
    from: "of",
    perPage: "Per page",
    filtered: "Filtered",
    incomeShort: "Income",
    expenseShort: "Expense",
    addAccountFirstTitle: "Add an account first",
    exportSuccessJson: "Successfully exported JSON",
    exportFailed: "Failed to export data",
    deleteSuccess: "Transaction deleted successfully",
    deleteFailed: "Failed to delete transaction",
    deleteBulkFailed: "Failed to delete selected transactions",

    // Budget
    budgetTitle: "Monthly Budget",
    totalBudget: "Total Budget",
    totalSpent: "Total Spent",
    remaining: "Remaining",
    noBudgetSet: "No budgets set",
    setBudget: "Set Budget",
    editBudget: "Edit Budget",
    deleteBudget: "Delete Budget",
    spent: "Spent",
    overBudget: "Over budget",
    underBudget: "Under budget",

    // Settings
    settingsTitle: "Settings",
    categoriesTab: "Categories",
    apiKeysTab: "API Keys",
    themeTab: "Theme",
    addCategory: "Add Category",
    deleteCategory: "Delete category",
    categoryDeleted: "Category deleted successfully",
    categoryDeleteFailed: "Failed to delete category",
    categoryCreated: "Category added successfully",
    categoryCreateFailed: "Failed to add category",
    confirmDeleteCategory: "Are you sure you want to delete",
    categoryDeleteWarning: "Transactions using this category will have their category cleared (transaction data remains safe).",

    // Investments
    investments: "Investments",
    portfolio: "Portfolio",
    totalValue: "Total Value",
    totalCost: "Total Cost",
    totalPnl: "Total P&L",
    buyAsset: "Buy Asset",
    sellAsset: "Sell Asset",
    updatePrice: "Update Price",
    noInvestments: "No investment assets yet",
    quantity: "Quantity",
    buyPrice: "Buy Price",
    currentPrice: "Current Price",
    marketValue: "Market Value",
    pnl: "P&L",

    // Goals
    goals: "Savings Goals",
    addGoal: "Add Goal",
    goalsPageSubtitle: "Manage and plan your future financial targets.",
    targetAmount: "Target Amount",
    currentAmount: "Saved",
    targetDate: "Target Date",
    totalTargetAmount: "TOTAL TARGET AMOUNT",
    totalSaved: "TOTAL SAVED",
    averageProgress: "AVERAGE PROGRESS",
    noGoalsSet: "No savings goals yet",
    noGoalsDesc: "Define your financial targets today like vacations, emergency funds, or buying a house!",
    createFirstGoal: "Create First Goal",
    dueLabel: "Due:",
    deleteGoalTitle: "Delete Savings Goal?",
    deletePermanentDesc: "This action is permanent and cannot be undone.",
    goalUpdateSuccess: "Savings goal updated successfully",
    goalAddSuccess: "Savings goal added successfully",
    goalDeleteSuccess: "Savings goal deleted successfully",
    goalDeleteFailed: "Failed to delete goal",
    pctNiceStart: "Nice Start",
    pctHalfway: "Halfway",
    pctAlmostDone: "Almost Done",
    pctCompleted: "Completed!",
    projectionDueNow: "Due now!",
    projectionAchieved: "Achieved! 🎉",
    projectionLeft: "left",
    projectionMonth: "/ mo",
    valGoalNameRequired: "Goal name is required",
    valGoalTargetAmount: "Target amount must be greater than 0",
    valGoalCurrentAmount: "Current amount is invalid",
    valGoalDateRequired: "Target date is required",
    valGoalSaveFailed: "Failed to save",
    editGoalTitle: "Edit Savings Goal",
    newGoalTitle: "New Savings Goal",
    goalSubtitle: "Measure and track your financial objectives.",
    goalNameLabel: "Goal Name",
    goalNamePlaceholder: "e.g. New Laptop",
    linkedAccountLabel: "Linked Account (Optional)",
    noAccountLinked: "No account",
    selectAccountPlaceholder: "Select account",
    noteOptionalLabel: "Note (optional)",
    noteOptionalPlaceholder: "e.g. Save from annual bonus",
    savingLabel: "Saving...",
    saveChanges: "Save Changes",
    selectDatePlaceholder: "Select Date",

    // Recurring
    recurring: "Recurring Bills",
    addRecurring: "Add Bill",
    frequency: "Frequency",
    autoPay: "Auto-Pay",
    nextPayment: "Next Payment",
    billSchedule: "Bill Schedule & Subscriptions",
    totalMonthlyCommitment: "TOTAL MONTHLY COMMITMENT",
    activeSubscriptions: "ACTIVE SUBSCRIPTIONS",
    setupBill: "Setup Bill",
    payNow: "Pay Now",
    deleteRecurringTitle: "Delete Recurring Bill?",
    deleteRecurringDesc: "Are you sure you want to delete this recurring bill?",

    // Theme Settings
    themeCustomizer: "Theme Customizer",
    customThemeLabel: "Custom Theme Colors",
    accentColor: "Accent Color",
    canvasColor: "Canvas Color",
    surfaceColor: "Card/Surface Color",
    borderColor: "Border Color",
    successColor: "Success/Income Color",
    dangerColor: "Danger/Expense Color",
    saveTheme: "Save Theme Design",
    resetTheme: "Reset Theme",

    // Common
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    create: "Create",
    loading: "Loading...",
    error: "An error occurred",
    success: "Success",
    confirm: "Confirm",
  }
};

type Language = "id" | "en";

interface LanguageContextProps {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: keyof typeof translations.id) => string;
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== "undefined") {
      const stored = localStorage.getItem("app-language");
      if (stored === "id" || stored === "en") return stored;
    }
    return "id";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    if (typeof window !== "undefined") {
      localStorage.setItem("app-language", lang);
    }
  };

  const t = (key: keyof typeof translations.id): string => {
    return translations[language][key] || translations["id"][key] || String(key);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
